### ISSUE TITLE
Breaks with bad urls

### ISSUE THREAD

**Issue by tsteuwer** [angular-material-extensions/link-preview#16]
This field is incredibly small on mobile so I cant read everything right now but it breaks in chrome mobile on my pixel XL by using this text: "I looked at google.com and noticed something badurl.derp.io". Shows Google, then a spinner underneath, then a broken image with a large border around it. This was using the demo page.

**Comment by AnthonyNahas** [comment]
@tsteuwer thanks for reporting! I will improve the demo app and fix the bugs related to the broken image while fetching a link! I will patch soon the libraray

**Comment by AnthonyNahas** [comment]
@tsteuwer bugs have been fixed
