### ISSUE TITLE
Unable to use package when importing it in app module. NullInjectorError: No provider for InjectionToken.

### ISSUE THREAD

**Issue by tetiana-batsenko-windmill** [angular-material-extensions/link-preview#50]
### OS and Version?
macOS Mojave

### Versions
node: 10.14.1
npm: 6.4.1
angular: 7.0.4

### Repro steps
Just follow the instructions in README.md of this repo and import module in your app module.

### The log given by the failure
NullInjectorError: No provider for InjectionToken NgxLinkifyjsConfig! ; Zone: <root> ; Task: Promise.then ; Value: Error: "StaticInjectorError(AppModule)[NgxLinkifyjsModule -> InjectionToken NgxLinkifyjsConfig]

### Desired functionality
It should import without errors.

**Comment by AnthonyNahas** [comment]
I've just patched the library! [Version 1.1.1](https://www.npmjs.com/package/@angular-material-extensions/link-preview) is now out! 

Thanks for reporting!
